### ISSUE TITLE
import button via ajax in single page article

### ISSUE THREAD

**Issue by marcelmastel** [Laravel-Backpack/Docs#34] opened 2019-01-25 15:20 UTC
I would like search images in storage upload  and 
if article title is in name file 'title-article.jpg' for example associate image automatically.

All via Ajax.
It is possibile?

For Example:
Add field button "import images" in page article.
When click button, search in storage upload, and if files exist response it in view.

**Comment by tabacitu** [comment] 2019-03-03 09:34
Hi @marcelmastel ,

Yes, it should totally be possible. See how to add [create a custom button](https://backpackforlaravel.com/docs/3.6/crud-buttons#adding-a-custom-button-with-a-blade-file) here. You can also take a look at [the "delete" button in the core package](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/buttons/delete.blade.php) - it uses AJAX, you could re-use some of the code. 

I'm going to close this, as it's definitely not a bug. Please use Github only for bugs.
Cheers!

**Closed by tabacitu** 2019-03-03 09:34 UTC
Labels: triage
